# Generated by Django 3.1.2 on 2020-11-15 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KimetsuCharactorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('characteristic', models.CharField(max_length=300)),
                ('create_dt', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SexModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_id', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=10)),
                ('create_dt', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
